import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

/**
 * Flat-config ESLint (v3.3 §1.7) — replaces the deprecated `next lint`.
 * eslint-config-next (core-web-vitals) + its TypeScript support; runs
 * non-interactively via `npm run lint` and exits non-zero on errors, so it
 * joins the phase gate alongside typecheck/tests/build.
 */

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      // next-env.d.ts is generated by Next on every dev/build run.
      "next-env.d.ts",
      ".next/**",
      "out-native/**",
      "node_modules/**",
      "public/sw.js",
      "public/sw.template.js",
      "ios/**",
      "android/**",
    ],
  },
];

export default config;
