import type { AssessmentDef } from "./defs";

/**
 * Wave 2 question banks (Phase NEXT, workstream B): Emotional Intelligence
 * Profile and Trauma-Response & Coping Profile. Same architecture and
 * register as wave 1 — educational self-report, mirrored pairs for the
 * validity system, attention checks that say what they are, every band a
 * legitimate place to be. The trauma profile never claims PTSD/CPTSD and
 * carries a professional-support pathway in its result note.
 */

export const EMOTIONAL_INTELLIGENCE: AssessmentDef = {
  id: "emotionalIntelligence",
  name: "Emotional Intelligence Profile",
  tagline: "How you read, regulate, and repair — the skills under every relationship.",
  minutes: 6,
  kind: "likert",
  resultNote:
    "Emotional intelligence is a set of trainable skills, not a fixed gift. Every band below has a concrete practice attached — the Mind and Skills tabs hold the tools.",
  traits: [
    {
      key: "selfAwareness",
      label: "Self-awareness",
      blurb: "noticing what you're feeling while you're still feeling it",
      high: "You catch your emotional weather early — that's the foundation skill. Keep naming feelings specifically; \"frustrated\" beats \"bad\".",
      low: "Feelings tend to register late, often after they've already steered you. The daily mood check-in is exactly this muscle — two honest words a day builds it.",
      balanced: "You notice the big waves and sometimes miss the undertow. Naming feelings mid-conversation is the next level.",
    },
    {
      key: "selfRegulation",
      label: "Self-regulation",
      blurb: "the gap you can hold between feeling something and acting on it",
      high: "You can feel strongly without being driven by it. Guard this under sleep loss — regulation is the first thing fatigue taxes.",
      low: "Feelings tend to convert to action fast — quick words, quick purchases, quick exits. The 60-second breathing reset exists to widen exactly that gap.",
      balanced: "You hold the gap most days and lose it under stack-ups. Knowing your overload signs is the practice.",
    },
    {
      key: "empathy",
      label: "Empathy",
      blurb: "reading what others feel (cognitive) and feeling it with them (affective) — two different skills that often score differently",
      high: "You track other people's inner weather well. One distinction worth knowing: understanding what someone feels (cognitive empathy) and feeling it with them (affective empathy) are separate skills — strength in one doesn't guarantee the other.",
      low: "Other people's emotional signals arrive faintly or late for you. That's a skill gap, not a character verdict — asking \"what was that like for you?\" and actually waiting builds it.",
      balanced: "You read people reasonably well, more easily when you're not stressed yourself. Empathy has a battery; protect it.",
    },
    {
      key: "accountability",
      label: "Accountability",
      blurb: "owning your part without collapsing into shame or deflecting into blame",
      high: "You can say \"that was mine\" without theatrics. That single skill de-escalates most conflicts faster than any technique.",
      low: "Owning mistakes tends to feel dangerous, so explanations arrive before ownership does. Practice the two-sentence version: what I did, what I'll do differently. Full stop.",
      balanced: "You own your part when you feel safe and defend it when you don't. Notice which company brings out which.",
    },
    {
      key: "repair",
      label: "Repair ability",
      blurb: "moving back toward someone after friction, first",
      high: "You initiate repair instead of waiting for it — the strongest predictor of relationships that last. Keep going first.",
      low: "After friction you tend to wait — for them, for time, for it to fade. Repair is a move, not a mood: one calm sentence within a day changes the whole pattern.",
      balanced: "You repair when the stakes are obvious and let small rifts silt up. Small repairs are the cheap ones.",
    },
    {
      key: "perspectiveTaking",
      label: "Perspective-taking",
      blurb: "genuinely trying on the other side's view, especially mid-disagreement",
      high: "You can hold your view and theirs at once — rare under heat. It makes you dangerous in the best way in any negotiation.",
      low: "Under disagreement, your view tends to fill the whole frame. One practice: state their position so well they'd sign it, before you answer it.",
      balanced: "You can take perspectives when calm; heat narrows you like it narrows everyone. Buy calm first, then think.",
    },
    {
      key: "defensiveness",
      label: "Defensiveness under stress",
      blurb: "how much feedback feels like attack when you're already stretched",
      high: "Feedback lands as threat when you're stressed, and the shields go up fast. The shields are the thing to work on, not the people holding the mirrors.",
      low: "You can hear hard feedback without armoring — even stressed. That openness is worth more than talent in most rooms.",
      balanced: "You take feedback well until you're depleted, then it stings. Timing your hard conversations is legitimate strategy.",
    },
  ],
  questions: [
    { id: "eqsa1", kind: "likert", trait: "selfAwareness", text: "I can usually name what I'm feeling while it's happening." },
    { id: "eqsa2", kind: "likert", trait: "selfAwareness", text: "I often only realize I was angry or hurt hours later.", reverse: true },
    { id: "eqsa3", kind: "likert", trait: "selfAwareness", text: "I notice early body signs of stress — jaw, shoulders, stomach." },
    { id: "eqsr1", kind: "likert", trait: "selfRegulation", text: "I can feel a strong urge and still choose not to act on it." },
    { id: "eqsr2", kind: "likert", trait: "selfRegulation", text: "When I'm upset, things come out of my mouth I didn't plan to say.", reverse: true },
    { id: "eqsr3", kind: "likert", trait: "selfRegulation", text: "I can pause an argument and come back to it calmer." },
    { id: "eqatt1", kind: "attention", text: "To show you're reading, choose \"Agree\" for this one.", expected: 4 },
    { id: "eqem1", kind: "likert", trait: "empathy", text: "I usually sense how someone feels before they say it." },
    { id: "eqem2", kind: "likert", trait: "empathy", text: "When someone describes their pain, something in me feels it too." },
    { id: "eqem3", kind: "likert", trait: "empathy", text: "People's emotional reactions often catch me completely off guard.", reverse: true },
    { id: "eqac1", kind: "likert", trait: "accountability", text: "When I mess up, I say so plainly before explaining anything." },
    { id: "eqac2", kind: "likert", trait: "accountability", text: "My first instinct when criticized is to point at the circumstances.", reverse: true },
    { id: "eqac3", kind: "likert", trait: "accountability", text: "I can apologize without adding a \"but\"." },
    { id: "eqrp1", kind: "likert", trait: "repair", text: "After a fight, I'm usually the one who reaches out first." },
    { id: "eqrp2", kind: "likert", trait: "repair", text: "I let tension sit for days rather than reopen it.", reverse: true },
    { id: "eqatt2", kind: "attention", text: "Attention check: choose \"Strongly disagree\" here.", expected: 1 },
    { id: "eqpt1", kind: "likert", trait: "perspectiveTaking", text: "Mid-disagreement, I genuinely try to state the other side's case fairly." },
    { id: "eqpt2", kind: "likert", trait: "perspectiveTaking", text: "When I'm sure I'm right, the other view stops registering.", reverse: true },
    { id: "eqdf1", kind: "likert", trait: "defensiveness", text: "When I'm stressed, even gentle feedback feels like an attack." },
    { id: "eqdf2", kind: "likert", trait: "defensiveness", text: "I can hear hard feedback on a bad day without shutting down.", reverse: true },
    { id: "eqdf3", kind: "likert", trait: "defensiveness", text: "People close to me say I get prickly when I'm overwhelmed." },
  ],
};

export const TRAUMA_COPING: AssessmentDef = {
  id: "traumaCoping",
  name: "Trauma-Response & Coping Profile",
  tagline: "The protective patterns your system learned — named without judgment.",
  minutes: 6,
  kind: "likert",
  resultNote:
    "These are coping patterns, not diagnoses — this profile cannot assess or rule out PTSD or any other condition; only a licensed clinician can do that. Patterns that once protected you can outlive their usefulness, and they respond well to skilled help: if several run high here and they're costing you, a trauma-informed therapist is the strongest move on this page.",
  traits: [
    {
      key: "fightFlight",
      label: "Fight / flight activation",
      blurb: "how quickly your system escalates to confrontation or exit under threat",
      high: "Under pressure your system moves — argue harder or get out now. That speed once protected you. The work is inserting one breath between trigger and launch; the Mind reset is built for exactly that.",
      low: "Escalation isn't your system's first move — you stay engaged without fighting or fleeing. That's regulation capital most people have to earn.",
      balanced: "You escalate when it's proportionate and mostly stay steady. Watch the exceptions — they usually share a trigger.",
    },
    {
      key: "freezeShutdown",
      label: "Freeze / shutdown & numbness",
      blurb: "going still, blank, or emotionally offline when things overwhelm",
      high: "When it's too much, your system goes quiet — blank mind, flat feelings, autopilot. That's a protective circuit, not laziness or coldness. Gentle re-entry (movement, cold water, naming five things you can see) beats forcing yourself to \"snap out of it\".",
      low: "You stay present and feeling even in heavy moments. Remember that others who go quiet may be circuit-breaking, not stonewalling.",
      balanced: "You mostly stay online, with occasional blank-outs under real overload. Note what precedes them.",
    },
    {
      key: "fawn",
      label: "Fawn / people-pleasing",
      blurb: "managing threat by managing other people's feelings — agreement as armor",
      high: "Keeping everyone pleased has been a survival strategy, and it works — at the price of your own wants going unread, even by you. The practice: one honest \"no\" a week, small stakes first. The boundary-script tool in Mind is the gym for this.",
      low: "You don't reflexively bend to keep the peace. Your agreements mean something because your refusals do.",
      balanced: "You accommodate freely but not compulsively. Check the exceptions: who can you not say no to?",
    },
    {
      key: "hypervigilance",
      label: "Hypervigilance",
      blurb: "the scanner that never quite powers down — reading rooms, tones, exits",
      high: "Your threat-scanner runs hot: you read moods, exits, and shifts other people miss entirely. It's exhausting because it never clocks out. Body-based downshifts (long exhales, weight, warmth) speak its language better than reassurance does.",
      low: "Your baseline is trust — rooms feel neutral until proven otherwise. That's what a nervous system at rest looks like.",
      balanced: "You scan in unfamiliar territory and relax in known company — the calibrated version.",
    },
    {
      key: "avoidance",
      label: "Avoidance",
      blurb: "steering wide of places, topics, and feelings that touch the old material",
      high: "Whole territories — conversations, places, memories — are cordoned off. Avoidance genuinely works short-term and quietly shrinks life long-term. The counter isn't force; it's approaching the edges in small, chosen doses, ideally with support.",
      low: "You can approach hard topics and places without wide detours. That willingness is what keeps the map from shrinking.",
      balanced: "Some things you face, some you route around. Worth asking which detours still earn their cost.",
    },
    {
      key: "rumination",
      label: "Rumination",
      blurb: "the replay loop — old scenes and arguments running on repeat",
      high: "Your mind reruns the tape looking for the frame where it could have gone differently. The loop feels like problem-solving but doesn't solve — scheduled worry time and the thought-record tool interrupt it better than willpower.",
      low: "You process and file — events end when they end. That's a clean burn most ruminators would trade for.",
      balanced: "You replay the big ones for a while, then set them down. Normal digestion, not a loop.",
    },
    {
      key: "boundaries",
      label: "Boundary difficulty",
      blurb: "how hard it is to know, state, and hold your own lines",
      high: "Your lines blur — you feel the violation only afterward, or state the boundary and cave when tested. Boundaries are a learnable sequence: know it, say it once plainly, hold it without re-arguing. Start where the stakes are small.",
      low: "You know your lines and hold them without drama. That clarity is protective for you and honestly for everyone around you.",
      balanced: "You hold boundaries with most people and lose them with a specific few. The few are the curriculum.",
    },
  ],
  questions: [
    { id: "tcff1", kind: "likert", trait: "fightFlight", text: "When conflict starts, my body is instantly ready to argue or leave." },
    { id: "tcff2", kind: "likert", trait: "fightFlight", text: "I stay physically calm during confrontation.", reverse: true },
    { id: "tcff3", kind: "likert", trait: "fightFlight", text: "I've walked out of situations abruptly because staying felt unbearable." },
    { id: "tcfz1", kind: "likert", trait: "freezeShutdown", text: "Under real stress my mind goes blank and words get hard to find." },
    { id: "tcfz2", kind: "likert", trait: "freezeShutdown", text: "There are stretches where I feel emotionally flat — present but not really feeling." },
    { id: "tcfz3", kind: "likert", trait: "freezeShutdown", text: "I stay emotionally present even in overwhelming moments.", reverse: true },
    { id: "tcatt1", kind: "attention", text: "To show you're reading, choose \"Disagree\" for this one.", expected: 2 },
    { id: "tcfw1", kind: "likert", trait: "fawn", text: "I agree to things I don't want, to keep someone's mood okay." },
    { id: "tcfw2", kind: "likert", trait: "fawn", text: "I often don't know what I want until I know what everyone else wants." },
    { id: "tcfw3", kind: "likert", trait: "fawn", text: "Saying no feels straightforward to me, even to people I love.", reverse: true },
    { id: "tchv1", kind: "likert", trait: "hypervigilance", text: "In any room, I track moods, exits, and who's tense — automatically." },
    { id: "tchv2", kind: "likert", trait: "hypervigilance", text: "A small shift in someone's tone can put my whole system on alert." },
    { id: "tchv3", kind: "likert", trait: "hypervigilance", text: "New places and people feel neutral to me until something actually happens.", reverse: true },
    { id: "tcatt2", kind: "attention", text: "Attention check: choose \"Strongly agree\" here.", expected: 5 },
    { id: "tcav1", kind: "likert", trait: "avoidance", text: "There are topics, places, or memories I organize my life around not touching." },
    { id: "tcav2", kind: "likert", trait: "avoidance", text: "I'd rather feel a hard thing now than spend energy dodging it.", reverse: true },
    { id: "tcru1", kind: "likert", trait: "rumination", text: "Old arguments and moments replay in my head long after they end." },
    { id: "tcru2", kind: "likert", trait: "rumination", text: "Once something's over, I rarely think about it again.", reverse: true },
    { id: "tcbd1", kind: "likert", trait: "boundaries", text: "I often realize a line was crossed only after I'm already resentful." },
    { id: "tcbd2", kind: "likert", trait: "boundaries", text: "When I state a limit, I hold it even when someone pushes.", reverse: true },
    { id: "tcbd3", kind: "likert", trait: "boundaries", text: "I re-explain and re-justify my boundaries until they erode." },
  ],
};

export const COGNITIVE_SKILLS: AssessmentDef = {
  id: "cognitiveSkills",
  name: "Cognitive Skills Profile",
  tagline: "Pattern, memory, reasoning, speed — a training baseline, not a rating of you.",
  minutes: 5,
  kind: "likert",
  introNote:
    "This is not a formal IQ test. It is a self-improvement-oriented cognitive skills profile. Each mini-task runs against a visible timer; a calm, ordinary day gives the truest baseline.",
  resultNote:
    "This is not a formal IQ test. It is a self-improvement-oriented cognitive skills profile — a baseline to train against, sensitive to sleep, stress, and caffeine like every cognitive measure. Retake it monthly and watch the trend, not the single number.",
  traits: [
    {
      key: "patternRecognition",
      label: "Pattern recognition",
      blurb: "spotting the rule in what you're looking at — and the piece that breaks it",
      high: "You extract structure fast. Feed it: the meta-learning skill track sharpens exactly this.",
      low: "Patterns took longer to surface today — attention and rest move this more than people expect. Train it playfully, not anxiously.",
      balanced: "Solid structural reading with room to speed up. Repetition converts deliberate spotting into instant seeing.",
    },
    {
      key: "workingMemory",
      label: "Working memory",
      blurb: "how much you can hold and use at once before it slips",
      high: "You hold a lot in the air at once. Externalize anyway — checklists free that capacity for thinking instead of storing.",
      low: "Holding items under time pressure leaked today. This is the most trainable scale here — and the best-supported by tools: write things down, chunk them, repeat them back.",
      balanced: "A dependable buffer that fills under load. Chunking (grouping digits, ideas, steps) is the multiplier.",
    },
    {
      key: "verbalReasoning",
      label: "Verbal reasoning",
      blurb: "seeing how words and categories relate — the odd one out, the shared thread",
      high: "Language is a precision tool for you — categories and relations come quickly.",
      low: "Verbal categories ran slower today. Reading anything demanding 15 minutes a day is the honest training plan.",
      balanced: "You reason through language reliably, faster in familiar territory.",
    },
    {
      key: "processingSpeed",
      label: "Processing speed & attention",
      blurb: "clean, quick scanning under a clock — accuracy first, speed second",
      high: "Fast and clean under the clock. Protect the inputs: sleep debt taxes this scale first.",
      low: "Scanning ran deliberate today — which is also what careful looks like. Speed follows accuracy in training; never the other way around.",
      balanced: "A steady scan rate that holds accuracy. Short, regular practice beats occasional sprints.",
    },
  ],
  questions: [
    { id: "cgp1", kind: "timed", trait: "patternRecognition", task: "patternGrid", timeLimitMs: 15000,
      prompt: "One of these breaks the pattern. Which?",
      options: ["▲▲", "■■", "●●", "◆▼"], correctIndex: 3 },
    { id: "cgp2", kind: "timed", trait: "patternRecognition", task: "patternGrid", timeLimitMs: 15000,
      prompt: "Continue the sequence: 2, 4, 8, 16, …",
      options: ["18", "24", "32", "64"], correctIndex: 2 },
    { id: "cgp3", kind: "timed", trait: "patternRecognition", task: "patternGrid", timeLimitMs: 18000,
      prompt: "AZ, BY, CX, … what comes next?",
      options: ["DW", "DV", "EW", "CW"], correctIndex: 0 },
    { id: "cgm1", kind: "timed", trait: "workingMemory", task: "digitRecall", timeLimitMs: 10000,
      memorize: "7 2 9 4", memorizeMs: 3000,
      prompt: "Which sequence did you just see?",
      options: ["7 2 9 4", "7 9 2 4", "2 7 9 4", "7 2 4 9"], correctIndex: 0 },
    { id: "cgm2", kind: "timed", trait: "workingMemory", task: "digitRecall", timeLimitMs: 10000,
      memorize: "3 8 1 6 5", memorizeMs: 3500,
      prompt: "Which sequence did you just see — reversed?",
      options: ["5 6 1 8 3", "3 8 1 6 5", "5 1 6 8 3", "6 5 1 8 3"], correctIndex: 0 },
    { id: "cgm3", kind: "timed", trait: "workingMemory", task: "digitRecall", timeLimitMs: 12000,
      memorize: "K 4 T 9 2 M", memorizeMs: 4000,
      prompt: "How many NUMBERS were in what you just saw?",
      options: ["2", "3", "4", "5"], correctIndex: 1 },
    { id: "cgatt1", kind: "attention", text: "Quick check between tasks: choose \"Agree\" here.", expected: 4 },
    { id: "cgv1", kind: "timed", trait: "verbalReasoning", task: "verbalOddOne", timeLimitMs: 12000,
      prompt: "Which word doesn't belong?",
      options: ["Oak", "Maple", "Birch", "Granite"], correctIndex: 3 },
    { id: "cgv2", kind: "timed", trait: "verbalReasoning", task: "verbalOddOne", timeLimitMs: 15000,
      prompt: "Glove is to hand as sock is to…",
      options: ["Shoe", "Foot", "Leg", "Wool"], correctIndex: 1 },
    { id: "cgv3", kind: "timed", trait: "verbalReasoning", task: "verbalOddOne", timeLimitMs: 15000,
      prompt: "Which pair relates the same way as \"author : book\"?",
      options: ["reader : page", "composer : symphony", "library : shelf", "pen : ink"], correctIndex: 1 },
    { id: "cgs1", kind: "timed", trait: "processingSpeed", task: "symbolMatch", timeLimitMs: 8000,
      prompt: "How many ◆ in:  ◆ ◇ ◆ ◆ ◇ ◆",
      options: ["3", "4", "5"], correctIndex: 1 },
    { id: "cgs2", kind: "timed", trait: "processingSpeed", task: "symbolMatch", timeLimitMs: 8000,
      prompt: "How many vowels in:  T R A I N E D",
      options: ["2", "3", "4"], correctIndex: 1 },
    { id: "cgs3", kind: "timed", trait: "processingSpeed", task: "symbolMatch", timeLimitMs: 9000,
      prompt: "Count the 8s:  3 8 5 8 2 8 8 1",
      options: ["3", "4", "5"], correctIndex: 1 },
  ],
};
